apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: mastodon-stream.yaml
spec:
  flows:
    - route:
        from:
          uri: vertx:public.source
          steps:
            - to:
                uri: stream:out
                description: Send JSON body to stdout
          description: Consume JSON data from the Vert.x event bus
    - route:
        from:
          uri: stream:http?httpUrl=https://foojay.social/api/v1/streaming/public
          steps:
            - split:
                expression:
                  tokenize:
                    token: '"\n"'
                description: Split SSE data by newlines
            - filter:
                expression:
                  simple:
                    expression: '${body} startsWith "data: {"'
                description: 'Filter for items which start with ''data: {'''
            - transform:
                expression:
                  simple:
                    expression: '${body.replaceAll("^data: *", "")}'
                    resultType: java.lang.String
                description: 'Strip off the leading ''data: '' to expose the raw JSON'
            - unmarshal:
                json:
                  library: gson
                  unmarshalType: java.util.Map
                description: Deserialize the JSON data into a Java Map
            - filter:
                expression:
                  simple:
                    expression: ${body.get("language").toLowerCase()} == "en"
            - setBody:
                expression:
                  simple:
                    expression: |-
                      {
                          "account": "${in.body.get("account").get("acct")}",
                          "content": "${in.body.get("content")}",
                          "created": "${in.body.get("created_at")}"
                      }
                description: >-
                  Using the extracted data, create a JSON body with the desired
                  fields
            - to:
                uri: vertx:public.source
                description: Send the JSON body via Vert.x event bus
