apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: mastodon-stream.yaml
spec:
  flows:
    - route:
        id: route-bc34
        from:
          uri: vertx:public.source
          id: from-fa3c
          description: Consume JSON data from the Vert.x event bus
          uri: vertx
          parameters:
            address: public.source
          steps:
            - to:
                uri: stream:out
                id: to-679c
                description: Send JSON body to stdout
    - route:
        id: route-9e58
        from:
          uri: stream:http?httpUrl=https://foojay.social/api/v1/streaming/public
          id: from-7165
          description: Get Mastodon events via SSE
          steps:
            - split:
                id: split-3253
                expression:
                  tokenize:
                    token: '"\n"'
                    id: tokenize-5997
                description: Split SSE data by newlines
            - filter:
                id: filter-6596
                expression:
                  simple:
                    expression: '${body} startsWith "data: {"'
                    id: simple-20f9
                description: Filter for data elements
            - transform:
                id: transform-3753
                expression:
                  simple:
                    expression: '${body.replaceAll("^data: *", "")}'
                    id: simple-9041
                    resultType: java.lang.String
                description: Extract JSON data
            - filter:
                id: filter-3891
                expression:
                  jsonpath:
                    expression: $[?(@.language == "en")]
                    id: jsonpath-6734
                description: Filter for only English posts
            - unmarshal:
                id: unmarshal-dbe5
                json:
                  id: json-ae49
                id: to-0e07
                description: Send JSON body to stdout
                uri: stream
                parameters:
                  kind: out
    - route:
        id: route-5852
        description: Produce Events From Mastodon
        from:
          id: from-7c84
          description: Get Mastodon events via SSE
          uri: stream
          parameters:
            kind: http
            httpHeaders: Authorization=Bearer 3KrtEW464T1vTL37yZeBGplbqDixkVsav_EwoF0qXXg
            httpUrl: https://foojay.social/api/v1/streaming/public
            scanStream: true
          steps:
            - split:
                id: split-7f4b
                description: Split SSE data by newlines
                expression:
                  tokenize:
                    id: tokenize-dfc5
                    token: '"\n"'
            - filter:
                id: filter-bdf5
                description: Filter for data elements
                expression:
                  simple:
                    id: simple-e9f5
                    expression: '${body} startsWith "data: {"'
            - transform:
                id: transform-826d
                description: Extract JSON data
                expression:
                  simple:
                    id: simple-3d65
                    expression: '${body.replaceAll("^data: *", "")}'
                    resultType: java.lang.String
            - filter:
                id: filter-a3d8
                description: Filter for only English posts
                expression:
                  jsonpath:
                    id: jsonpath-9bd5
                    expression: $[?(@.language == "en")]
            - unmarshal:
                id: unmarshal-418a
                description: Deserialize the JSON data into a Java Map
                json:
                  id: json-097f
                  library: gson
                  unmarshalType: java.util.Map
            - setBody:
                id: setBody-c210
                description: >-
                  Using the extracted data, create a JSON body with the desired
                  fields
                expression:
                  simple:
                    id: simple-d662
                    expression: >-
                      {"account":
                      "${in.body.get("account").get("acct")}","content":
                      "${in.body.get("content")}","created":
                      "${in.body.get("created_at")}"}
            - to:
                id: to-5418
                description: Send the JSON body via Vert.x event bus
                uri: vertx
                parameters:
                  address: public.source
                id: to-f873
                description: Send the JSON body via Vert.x event bus
