apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: mastodon-stream.yaml
spec:
  flows:
    - route:
        id: route-92c0
        from:
          uri: vertx:public.source
          id: from-59f2
          description: Consume JSON data from the Vert.x event bus
          steps:
            - to:
                uri: stream:out
                id: to-0e07
                description: Send JSON body to stdout
        description: Consume The Events
    - route:
        id: route-5852
        from:
          uri: stream:http?httpUrl=https://foojay.social/api/v1/streaming/public
          id: from-7c84
          description: Get Mastodon events via SSE
          steps:
            - split:
                id: split-7f4b
                expression:
                  tokenize:
                    token: '"\n"'
                    id: tokenize-dfc5
                description: Split SSE data by newlines
            - filter:
                id: filter-bdf5
                expression:
                  simple:
                    expression: '${body} startsWith "data: {"'
                    id: simple-e9f5
                description: Filter for data elements
            - transform:
                id: transform-826d
                expression:
                  simple:
                    expression: '${body.replaceAll("^data: *", "")}'
                    id: simple-3d65
                    resultType: java.lang.String
                description: Extract JSON data
            - filter:
                id: filter-a3d8
                expression:
                  jsonpath:
                    expression: $[?(@.language == "en")]
                    id: jsonpath-9bd5
                description: Filter for only English posts
            - unmarshal:
                id: unmarshal-418a
                json:
                  id: json-097f
                  library: gson
                  unmarshalType: java.util.Map
                description: Deserialize the JSON data into a Java Map
            - setBody:
                id: setBody-c210
                expression:
                  simple:
                    expression: |-
                      {
                          "account": "${in.body.get("account").get("acct")}",
                          "content": "${in.body.get("content")}",
                          "created": "${in.body.get("created_at")}"
                      }
                    id: simple-d662
                description: >-
                  Using the extracted data, create a JSON body with the desired
                  fields
            - to:
                uri: vertx:public.source
                id: to-5418
                description: Send the JSON body via Vert.x event bus
        description: Produce Events From Mastodon
