apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: twitter-stream.yaml
spec:
  flows:
    - route:
        from:
          uri: vertx:tweets
          steps:
            - to:
                uri: stream:out
    - route:
        from:
          uri: twitter-search:VenmoMe
          steps:
            - setBody:
                expression:
                  simple:
                    expression: "${body.getText}"
            - to:
                uri: vertx:tweets
          parameters:
            accessToken: '{{twitter.access.token}}'
            accessTokenSecret: '{{twitter.access.secret}}'
            consumerKey: '{{twitter.api.key}}'
            consumerSecret: '{{twitter.api.secret}}'
            type: polling
            count: 20
            delay: 5000
            greedy: true
            initialDelay: 0
